[package]

name = "libz-sys"
version = "0.1.6"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "z"
build = "build.rs"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/libz-sys"
description = """
Bindings to the system libz library (also known as zlib).
"""

[dependencies]
libc = "0.1"

[build-dependencies]
pkg-config = "0.3"
