[package]

name = "git2"
version = "0.2.12"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
readme = "README.md"
keywords = ["git"]
repository = "https://github.com/alexcrichton/git2-rs"
homepage = "https://github.com/alexcrichton/git2-rs"
documentation = "http://alexcrichton.com/git2-rs"
description = """
Bindings to libgit2 for interoperating with git repositories. This library is
both threadsafe and memory safe and allows both reading and writing git
repositories.
"""

[dependencies]
url = "0.2"
bitflags = "0.1"
libc = "0.1"
libgit2-sys = { path = "libgit2-sys", version = "0.2.3" }

[dev-dependencies]
docopt = "0.6"
rustc-serialize = "0.3"
time = "0.1"
tempdir = "0.3"

[features]
unstable = []
