language: rust
rust:
  - 1.0.0
  - 1.1.0
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cd docopt_macros;
      cargo build --verbose;
      cargo test --verbose;
    fi
