language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - export CARGO_TARGET_DIR=`pwd`/target
  - cargo test --no-default-features
  - cargo test
  - cargo run --manifest-path systest/Cargo.toml
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo test --features unstable;
      cargo test --manifest-path git2-curl/Cargo.toml;
    fi
  - cargo doc --no-deps
  - cargo doc --manifest-path=git2-curl/Cargo.toml --no-deps
  - cargo doc --manifest-path=libgit2-sys/Cargo.toml --no-deps
after_success:
  - travis-cargo --only nightly doc-upload
  - travis-cargo coveralls --no-sudo
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
env:
  global:
    secure: HlDs6Eyhy/67Wmqd6frmCnOMYQyqbv2ulL9qqqFF2zdlinJ2/Z0FDs+0GHNWu0BQ9v6+51KHbhieUaz3dTYDCKPlDiA2OmE8DQuXloxrrJfGmPLc1F+cKQGn5a5FrIrLJDkEpcfWXZItRtzSPkpVNEWGA66Osx50/Nd8lkdjFYA=
