[package]

name = "nom"
version = "1.2.0"
authors = [ "contact@geoffroycouprie.com" ]
description = "A byte-oriented, zero-copy, parser combinators library"
license = "MIT"
repository = "https://github.com/Geal/nom"
readme = "README.md"
documentation = "http://rust.unhandledexpression.com/nom/"
keywords = ["parser", "parser-combinators", "parsing", "streaming", "bit"]

include = [
  "CHANGELOG.md",
  "LICENSE",
  ".gitignore",
  ".travis.yml",
  "Cargo.toml",
  "src/*.rs",
  "tests/*.rs"
]

[features]
core = []
nightly = []
default = ["stream"]
regexp = ["regex"]
regexp_macros = ["regexp", "regex_macros"]
stream = []

[dependencies.regex]
version = "^0.1.41"
optional = true

[dependencies.regex_macros]
version = "^0.1.21"
optional = true

