[package]

name = "num_cpus"
version = "0.2.10"
description = "Get the number of CPUs on a machine."
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT"
repository = "https://github.com/seanmonstar/num_cpus"


[dependencies]
libc = "0.2"
winapi = "0.2"
kernel32-sys = "0.2"
