[package]

name = "libgit2-sys"
version = "0.3.7"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "git2"
build = "build.rs"
repository = "https://github.com/alexcrichton/git2-rs"
license = "MIT/Apache-2.0"
description = "Native bindings to the libgit2 library"

[lib]
name = "libgit2_sys"
path = "lib.rs"

[dependencies]
libssh2-sys = { version = "0.1.28", optional = true }
libc = "0.2"
libz-sys = "0.1.0"

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1.2"

[target.i686-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-linux-musl.dependencies]
openssl-sys = "0.7.0"
[target.aarch64-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.arm-unknown-linux-gnueabihf.dependencies]
openssl-sys = "0.7.0"
[target.i686-unknown-freebsd.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-freebsd.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-bitrig.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-openbsd.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-dragonfly.dependencies]
openssl-sys = "0.7.0"

[features]
ssh = ["libssh2-sys"]
https = []
