[package]

name = "url"
version = "1.1.0"
authors = ["The rust-url developers"]

description = "URL library for Rust, based on the WHATWG URL Standard"
documentation = "http://servo.github.io/rust-url/url/index.html"
repository = "https://github.com/servo/rust-url"
readme = "README.md"
keywords = ["url", "parser"]
license = "MIT/Apache-2.0"

[[test]]
name = "unit"

[[test]]
name = "data"
harness = false

[lib]
test = false

[dev-dependencies]
rustc-test = "0.1"
rustc-serialize = "0.3"

[features]
query_encoding = ["encoding"]
heap_size = ["heapsize", "heapsize_plugin"]

[dependencies]
idna = { version = "0.1.0", path = "./idna" }
heapsize = {version = ">=0.1.1, <0.4", optional = true}
heapsize_plugin = {version = "0.1.0", optional = true}
encoding = {version = "0.2", optional = true}
serde = {version = ">=0.6.1, <0.8", optional = true}
rustc-serialize = {version = "0.3", optional = true}
matches = "0.1"
