language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - export CARGO_TARGET_DIR=`pwd`/target
  - cargo build --verbose
  - cargo test --verbose
  - cargo test --verbose --features zlib
  - cargo test --verbose --features zlib --no-default-features
  - rustdoc --test README.md -L target/debug -L target/debug/deps
  - cargo doc --no-deps
  - cargo doc --no-deps --manifest-path=miniz-sys/Cargo.toml
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: tnY9uOzb+59QyxPwOkj64dYLhytJGEXCo3uMvlbFtBpNJ6B2bN+lFDLaILbki1xkIg6DOFLGGT0+2qLI295V8BgEOqs/bU1WNNTjCdIqhbYI+HrwPP2RocecIXCIrsmL7tVSqfdLnU8RCoS0CBvJOwX/f813UGn3yAP4k5l7K/U=
notifications:
  email:
    on_success: never
os:
  - linux
  - osx
