[package]
name = "libssh2-sys"
version = "0.1.33"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
links = "ssh2"
build = "build.rs"
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/ssh2-rs"
description = "Native bindings to the libssh2 library"

[lib]
name = "libssh2_sys"
path = "lib.rs"

[dependencies]
libz-sys = "0.1.0"
libc = "0.2"
ws2_32-sys = "0.2"
winapi = "0.2"

[target.i686-apple-darwin.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-apple-darwin.dependencies]
openssl-sys = "0.7.0"
[target.i686-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.aarch64-unknown-linux-gnu.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-linux-musl.dependencies]
openssl-sys = "0.7.0"
[target.arm-unknown-linux-gnueabihf.dependencies]
openssl-sys = "0.7.0"
[target.i686-unknown-freebsd.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-freebsd.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-dragonfly.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-bitrig.dependencies]
openssl-sys = "0.7.0"
[target.x86_64-unknown-openbsd.dependencies]
openssl-sys = "0.7.0"

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1.2"
